version: '3.4'

x-common:
  &common
  image: apache/airflow:2.3.4
  user: "root"  # Run the container with root privileges temporarily 
  env_file: 
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models 
    - ./requirements.txt:/sources/requirements.txt  # Mount requirements.txt
    - ./keys:/opt/airflow/keys/
    - /var/run/docker.sock:/var/run/docker.sock

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgres:
    image: postgres:13
    container_name: postgres-m3
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env

  scheduler:
    <<: [*common, *depends-on]
    # <<: *depends-on
    container_name: airflow-scheduler-m3
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"

  webserver:
    <<: [*common, *depends-on]
    # <<: *depends-on
    container_name: airflow-webserver-m3
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
  
  airflow-init:
    <<: *common
    container_name: airflow-init-m3
    entrypoint: /bin/bash
    command:
      - -c
      - |
        groupadd -f -g 50000 airflow && \ 
        mkdir -p /sources/logs /sources/dags /sources/plugins && \
        chown -R airflow:airflow /sources/{logs,dags,plugins} && \ 
        exec /entrypoint airflow version 
 